stages:
  - format
  - eslint
  - build

image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

format:
  stage: format
  script:
    - yarn
    - yarn format
    - git config user.name "CI Pipeline"
    - git config user.email "cipipeline@example.com"
    # stage some changes
    - git add .
    # We can use `-o ci.skip`, but AFAIK it doesn't work for Merge Request pipelines, while having it inside the commit message works there as well
    - git commit -m "A commit message [skip ci]"
    # we're on a detached head but we can push the commits we made to the remote branch like so:
    - git push origin HEAD:$CI_COMMIT_REF_NAME

eslint:
  stage: eslint
  dependencies:
    - format
  needs:
    - format
  cache:
    policy: pull
  script:
    - if [ ! -d "node_modules" ]; then yarn install; fi
    - yarn
    - yarn format
    - yarn lint

build:
  stage: build
  dependencies:
    - eslint
  needs:
    - eslint
  cache:
    policy: pull
  script:
    - if [ ! -d "node_modules" ]; then yarn install; fi
    - yarn build
